---
repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        description: Check formatting
        entry: npx prettier fnlock-switch-tp-comp-usb-kb\@goloshubov.github.io/ --check
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
